apiVersion: v1
kind: Service
metadata:
  name: temporal-money-transfer-server-service
  namespace: temporal-money-transfer
  labels:
    app: temporal-money-transfer-server
spec:
  ports:
  - port: 3000
    name: server
  type: ClusterIP
  selector:
    app: temporal-money-transfer-server