apiVersion: v1
kind: Service
metadata:
  name: temporal-money-transfer-server-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: temporal-money-transfer-server
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: server
  selector:
    app: temporal-money-transfer-server