apiVersion: v1
kind: Service
metadata:
  name: temporal-money-transfer-ui-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb   
  labels:
    app: temporal-money-transfer-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: ui
  selector:
    app: temporal-money-transfer-ui