apiVersion: v1
kind: Service
metadata:
  name: temporal-money-transfer-ui-service
  labels:
    app: temporal-money-transfer-ui
spec:
  ports:
  - port: 80
    name: ui
  type: ClusterIP
  selector:
    app: temporal-money-transfer-ui